= Open Apiary
Eric Sandbling, https://github.com/ericsandbling
:toc:
// :toc-title: Innehållsförteckning
:toclevels: 5
:sectnums:

A sustainable and ecologically conscious bee husbandry system designed for rational bee keeping.

== Introduction

The purpose of this repository is to develop a system for sustainable and ecologically conscious as well as rational bee husbandry.

At the outset of the project this is intended to include hive design as well as https://en.wikipedia.org/wiki/Information_and_communications_technology[ICT] systems surrounding the hive and the bee husbandry as a whole. ICT in this context might include features such as remote monitoring systems as well as cloud base diary tools for the apiarist.

== Read More

Read more in your language:

* link:docs/README.swe-SV.adoc[Svenska]

== Copyright

The content of this project itself is licensed under the https://creativecommons.org/licenses/by/3.0/[Creative Commons Attribution 3.0 Unported license], and the underlying source code used to format and display that content is licensed under the link:LICENSE.adoc[MIT license].
